src/index.ts, src/test/approve.spec.ts, src/types/index.ts, src/utils/getTokenData.ts, test-sdk.ts
Creation of `isRouteAppoved` & `approveRoute` methods
As I detect lot of repeated code I create the `validateRouteData` private method that retrieves all the data to be consumen inside of the public methods
Finally I also add support to send only feat, as this show interact directly with the axelar gateway and not squid main contract
- closes #208
- Zenhub issue: [128](https://app.zenhub.com/workspaces/squid-62f41ece0f99c000158e872d/issues/0xsquid/squid-core/128) [208](https://app.zenhub.com/workspaces/squid-62f41ece0f99c000158e872d/issues/0xsquid/squid-core/208) [166](https://app.zenhub.com/workspaces/squid-62f41ece0f99c000158e872d/issues/0xsquid/squid-core/166)
=> feat: add isRouteAppoved approveRoute & send support

package.json, src/constants/chains.ts, src/index.ts, src/scripts/sendOnly.ts, src/scripts/test-sdk.ts, src/scripts/tradeSend.ts, src/scripts/utils.ts, src/test/__snapshots__/sdk.spec.ts.snap, src/test/sdk.spec.ts, src/types/index.ts, src/utils/getChainData.ts, src/utils/getTokenData.ts
- Add cosmos chain configuration to squid sdk. 
- Add test script for sendOnly and tradeSendOnly for cosmos chain as destination chain
- closes 0xsquid/squid-core # (issue number)
- Zenhub issue: 107
=> Add cosmos chain support

package.json, src/index.ts, src/types/index.ts
- Support new gas cost params under transaction request in route API response
=> Feat: Add support for gas parameter in transaction request

src/0xsquid/v1/route.ts, src/index.ts, src/types/index.ts
Fix the bug where the getRoute fails if quoteOnly flag is true. The fix is to refactor code and remove validation for transactionRequest property in validateRouteParam 
- closes 0xsquid/squid-core #820
- Zenhub issue: #820
=> Fix: transactionRequest validation quoteOnly

src/0xsquid/v1/route.spec.ts, src/0xsquid/v1/route.ts, src/0xsquid/v1/sdk-info.ts, src/types/index.ts
Rename enableForecall param in getRoute to enableExpress to align with express changes in API.
See https://github.com/0xsquid/squid-core/pull/898
=> chore: refactor getRoute param for express feature

src/0xsquid/v1/status.ts
- fix a bug when chain data object is undefined in status api response
=> fix: handle undefined chaindata in parse status

CHANGELOG.md, package.json, yarn.lock
we're having critical security issues on some dependencies
i'm investigating, mainly caused by release-it
one of the issue is on vm2 package: https://www.npmjs.com/package/vm2
but the package has been deprecated and still used on release-it, someone warned here: https://github.com/release-it/release-it/issues/1024
the other issues are around semver package, also mainly in release-it package
=> build: attempt fixing security issues

src/index.ts
Get a `fromAmount` based on `fromToken`, `toToken` and `toAmount`.
Example usage:
```js
const ETH = squid.getTokenData(
"0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
"1"
);
const USDC = squid.getTokenData(
"0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
"1"
);
const usdcToEth = await squid.getFromAmount({
fromToken: USDC,
toAmount: "1",
toToken: ETH
}); // expected: ~1600
const ethToUsdc = await squid.getFromAmount({
fromToken: ETH,
toAmount: "200",
toToken: USDC
}); // expected: ~0.12...
// you can also specify slippage percentage (default is 1.5%)
const usdcToEth3 = await squid.getFromAmount({
fromToken: USDC,
toAmount: "1",
toToken: ETH,
slippagePercentage: 3
}); // expected: ~1648
```
- closes 0xsquid/squid-core#2487
- [Zenhub issue](https://app.zenhub.com/workspaces/squid-62f41ece0f99c0 …
=> feat: add method to get from amount

CHANGELOG.md, package.json, src/index.ts, yarn.lock
- At the moment it's impossible to do any swap (ibc/wasm) from cosmos using ledger on keplr
- I'm pushing code (will need review) to make it possible (adding a converter to format our messages to be amino compatible)
- From my tests It's retro compatible with not using ledger, so basic keplr wallet still work
- Problem though:
- `IBC_TRANSFER_TYPE` (from cosmos to cosmos): 
- ✅  classic wallet - ✅  ledger
- `WASM_TYPE` (from cosmos to evm):
- ✅  classic wallet - ❌  ledger
=> fix: handle ledger amino messages

src/index.ts
If no chains are provided to `getAllBalances`, `getCosmosBalances`, and `getEvmBalances`, use all chains by default.
This snippet fetches balances for all EVM and Cosmos chains:
```js
const allBalances = await squid.getAllBalances({
cosmosAddresses: [
{
address: "cosmos1xv9tklw7d82sezh9haa573wufgy59vmwe6xxe5",
chainId: "cosmoshub-3",
coinType: 118
}
],
evmAddress: "0x344b63c2BcB4B61765083735e8F49Bb203415a33"
});
```
This snippet fetches balances for all EVM chains:
```js
const evmBalance = await squid.getEvmBalances({
userAddress: "0x344b63c2BcB4B61765083735e8F49Bb203415a33"
});
```
This snippet fetches balances for all Cosmos chains:
```js
const cosmosBalance = await squid.getCosmosBalances({
addresses: [
{
address: "cosmos1xv9tklw7d82sezh9haa573wufgy59vmwe6xxe5",
chainId: "cosmoshub-3", …
```
=> fix (v2): use all chains when no chains are specified

src/index.ts
If no chains are provided to `getAllBalances`, `getAllCosmosBalances`, and `getAllEvmBalances`, use all chains by default.
This snippet fetches balances for all EVM and Cosmos chains:
```js
const allBalances = await squid.getAllBalances({
cosmosAddresses: [
{
address: "cosmos1xv9tklw7d82sezh9haa573wufgy59vmwe6xxe5",
chainId: "cosmoshub-3",
coinType: 118
}
],
evmAddress: "0x344b63c2BcB4B61765083735e8F49Bb203415a33"
});
```
This snippet fetches balances for all EVM chains:
```js
const evmBalance = await squid.getAllEvmBalances({
userAddress: "0x344b63c2BcB4B61765083735e8F49Bb203415a33"
});
```
This snippet fetches balances for all Cosmos chains:
```js
const cosmosBalance = await squid.getAllCosmosBalances({
addresses: [
{
address: "cosmos1xv9tklw7d82sezh9haa573wufgy59vmwe6xxe5",
chainId: …
```
=> fix: use all chains when no chains are specified

src/index.ts
Setting memo to empty string if it's coming as "undefined" from our api
To fix the bug where amino converter "toAmino" is using omitDefault(memo) that throws an error if memo is undefined
=> fix: parse undefined memo sent from api

src/handlers/evm/utils.ts, src/types/index.ts
Add missing `chainId` property to evm balances response:
```diff
type TokenBalance = {
symbol: string;
address: string;
decimals: number;
balance: string;
+ chainId: string | number;
};
```
=> feat (v2): add chainId property to evm balances response

src/services/getEvmBalances.ts, src/types/index.ts
Add missing `chainId` property to evm balances response
```diff
type TokenBalance = {
symbol: string;
address: string;
decimals: number;
balance: string;
+ chainId: string | number;
};
```
=> feat (v1): add chainId property to evm balances response

src/adapter/HttpAdapter.ts, src/index.ts, src/types/http.ts, src/types/index.ts
Optionally set an HTTP timeout.  This is helpful for maintaining responsiveness for end users, especially for apps that might leverage multiple route APIs.
`yarn build && yarn test` and local end-to-end testing w/ Valora's squid integration.
=> feat: add a timeout to Config and Squid

src/services/getEvmBalances.ts
- use getBalance to fetch native tokens balance
- add Kava to the list of chains not supporting multicall
Running this script:
```ts
import { Squid } from "@0xsquid/sdk";
(async () => {
// instantiate the SDK
const squid = new Squid();
squid.setConfig({
baseUrl: "https://api.squidrouter.com", // for mainnet use "https://api.0xsquid.com"
integratorId: "squid-test"
});
// init the SDK
await squid.init();
console.log("Squid inited");
const evmBalances = await squid.getAllEvmBalances({
userAddress: "0x1f0b95d58090f3F08282c9c875519E741e7Cd045",
chains: ["2222"]
});
console.log({
evmBalances: evmBalances.filter(b => b.balance !== "0")
});
})();
```
Console output:
```js
Squid inited
{
evmBalances: [],
}
```
Console output:
```js
Squid inited
{
evmBalances: [
{
address: …
```
=> Fix v1/multicall balances

package.json, src/services/getEvmBalances.ts, yarn.lock
- Add Fraxtal to chains not supporting multicall
- Use custom multicall address to get balances
Script to fetch balance  for Blast:
```ts
import { Squid } from "@0xsquid/sdk";
(async () => {
const squid = new Squid();
squid.setConfig({
baseUrl: "https://squid-api-git-feat-blast-0xsquid.vercel.app",
integratorId: "squid-test"
});
await squid.init();
const evmBalances = await squid.getAllEvmBalances({
userAddress: "0xb13CD07B22BC5A69F8500a1Cb3A1b65618d50B22",
chains: [81457]
});
console.log({
evmBalances: evmBalances.filter(b => b.balance !== "0")
});
})();
```
Returns:
```js
{
evmBalances: [],
}
```
Returns:
```js
{
evmBalances: [
{
symbol: "ETH",
address: "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
decimals: 18,
balance: "6277774640826655",
chainId: 81457,
}, {
symbol: "axlUSDC", …
```
=> chore: add blast to chains not supporting multicall

package.json
This pr had been closed (but shouldn't be) https://github.com/0xsquid/squid-sdk/pull/280
Because current v1 npm version is https://www.npmjs.com/package/@0xsquid/sdk/v/1.14.14
So currently github action is throwing this error because of that
> ERROR fatal: tag 'v1.14.14' already exists
=> chore: fix wrong version

src/index.ts, src/test/fromAmount.spec.ts
In the previous version, we experienced fromAmount being noted for example as 4.0e-10 ETH
This was obviously breaking widget parsing before executing transaction
Tested locally with prod data on very small prices
Ex: buy item at 0.0001 axlUSDC, from ETH 
This was previously giving an error because of scientific notation
Now converting successfully to 0.0000000795343 ETH
=> fix: use bigNumber on getFromAmount method

src/index.ts
- Increase gas multiplier to 1.5 to resolve not enough gas issue on Nolus chain transactions.
- Nolus: NLS to Avalanche: AVAX
=> [v1] chore: increment cosmos gas multiplier to 1.5

package.json, yarn.lock
- upgrade squid types package to v0.1.85
=> chore: upgrade squid types package to v0.1.85

src/services/getEvmBalances.ts
When getting evm balances, if the RPC call fails (usually the rpc is broken) the sdk returns an empty array for tokens, instead of tokens with balance: 0. This ends up in the widget displaying an empty tokens list:
After the fix, the tokens load correctly (the underlying issue is not fixed though, the rpc is down)
=> fix: returns all tokens with zero balance when rpc call fails

src/handlers/evm/index.ts, src/handlers/evm/utils.ts, src/index.ts, src/types/index.ts
The wallet is already doing a balance check 
- add new param to route execution: `bypassBalanceChecks`
=> chore: remove balance check before executing route

.github/workflows/unit-tests.yml, src/adapter/HttpAdapter.ts, src/handlers/evm/index.spec.ts, src/handlers/evm/index.ts, src/index.spec.ts, src/index.ts, src/types/http.ts
In some rare cases, when a browser has multiple tabs of the same website open, some wallets need the `chainId` to be defined to prevent transactions from being sent to the wrong network.
- add `chainId` param to evm transactions
- fix tests
- add missing route properties
- rename axios' `baseUrl` to `baseURL`
- ![image](https://github.com/user-attachments/assets/75411378-5031-4e98-a2f2-23d91133e78c)
=> chore: add chainId param when sending evm transaction

package.json, yarn.lock
- bump axios to 1.8.2 to fix [possible SSRF and Credential Leakage vulnerability](https://github.com/advisories/GHSA-jr5f-v2jv-69x6)
- add patched axios version to package resolutions. This is needed for `@cosmjs/tendermint-rpc` which is on `axios@^1.6.0`
- regenerate lockfile, now using `registry.yarnpkg.com` registry url
Run `yarn audit`
```
16 vulnerabilities found - Packages audited: 1028
Severity: 13 Moderate | 3 High
```
```
1 vulnerabilities found - Packages audited: 1033
Severity: 1 High
```
=> chore: fix axios, regenerate lockfile

package.json, yarn.lock
- Upgraded ethers from 6.8.1 to 6.13.5 to update ws dependency
- ensuring ws version ≥8.17.1 is used
- yarn build ✅
- yarn test ✅
=> chore: update to latest ethers version

package.json, src/index.spec.ts, src/types/index.ts
I'll help you create a PR description for these changes. Let me analyze the changes first.
The changes involve:
1. Version bump from 2.9.5 to 2.9.6
2. Updates to the `GetStatus` type in `src/types/index.ts`:
- Making `quoteId` a required field (removing optional `?`)
- Adding optional `bridgeType` field
3. Test updates in `src/index.spec.ts` to include the required `quoteId` field
Here's a suggested PR description:
```markdown
- Made `quoteId` a required field in the `GetStatus` type
- Added optional `bridgeType` field to `GetStatus` type
- Updated test cases to include required `quoteId` field
The `GetStatus` type has been updated to:
- Make `quoteId` a required field (previously optional)
- Add new optional `bridgeType` field
- Updated test cases in `src/index.spec.ts` to include the …
```
=> add bridgetype to status and quoteid required

package.json, yarn.lock
- Update axios to v1.10.0 to get updated form-data dependency
- Add form-data resolution to force version 4.0.4 which includes security fix
- Resolves critical vulnerability CVE in form-data package
=> fix: resolve form-data vulnerability
