0xsquid/squid-sdk

.env.example
.gitignore
transaction.ts

- updated api-sdk to work with local fork version of squid

local fork compatibility

---

.env.eth
.env.example
README.md

Update README and env example file

fix: env example update readme

---

src/contants/infiniteApproval.ts
src/index.ts
src/test/__snapshots__/sdk.spec.ts.snap
src/test/approve.spec.ts
src/test/constants/chains.ts
src/test/constants/tokens.ts
src/test/sdk.spec.ts
src/types/index.ts

This PR adds infinite approval support for the SDK

feat: add executionSettings and infiniteApproval config

---

src/scripts/allowance-approve.ts
src/scripts/sendTrade.ts
src/scripts/test-sdk.ts
src/scripts/tradeSend.ts
src/scripts/tradeSendTrade.ts
src/scripts/utils.ts

fix: imports on integration scripts

---

src/scripts/sendTrade.ts
src/scripts/test-sdk.ts
src/scripts/tradeSend.ts
src/scripts/tradeSendTrade.ts
test-sdk.ts

amount was so low that the relay
service didn't execute the trade
- closes 0xsquid/squid-sdk #14

fix: USDC test amount

---

package.json
src/index.ts
src/scripts/allowance-approve.ts
src/scripts/test-sdk.ts
src/test/__snapshots__/sdk.spec.ts.snap
src/test/approve.spec.ts
src/test/sdk.spec.ts
src/types/index.ts
test-sdk.ts

refactor: erase env from sdk config

---

package.json
src/index.ts
src/types/index.ts

feat: add status method

---

package.json
src/index.ts
src/types/index.ts
test-sdk.ts

This PR aims to add the exchange rate between the source and destination tokens, so that logic has been added to the `getRoute` method.
The coingecko USD valuation came from the api so it's transparent for the SDK
- closes 0xsquid/squid-core#224
- [Zenhub issue: ](https://app.zenhub.com/workspaces/squid-62f41ece0f99c000158e872d/issues/0xsquid/squid-core/224)

feat: add exchange rate

---

package.json
src/index.ts

fix: signer address condition

---

package.json
src/index.ts
src/test/constants/chains.ts
src/types/index.ts
src/utils/getChainData.ts
src/utils/getTokenData.ts

fix: typing chainType

---

package.json
src/index.ts
src/types/index.ts

fix: types for dex route abstraction

---

package.json
src/index.ts
src/test/sdk.spec.ts

fix: remove exchange rate calculation from sdk to api

---

src/index.ts
src/test/__snapshots__/sdk.spec.ts.snap
src/test/sdk.spec.ts

fix: change init sdk variable name

---

package.json
src/index.ts
yarn.lock

fix: move dotenv dependencie to devDependencie

---

src/index.ts

Increase tx gas limit to 70e4 to align with curve update

feat: increase transaction gas limit

---

package.json
src/index.ts
src/types/index.ts

https://app.zenhub.com/workspaces/squid-62f41ece0f99c000158e872d/issues/0xsquid/squid-core/304

feat: add token type to route response

---

package.json
src/types/index.ts

fix: rename enableForecall

---

src/types/index.ts

Fix chainname for the goerli testnet

fix: add new chainname for testnet

---

package.json
src/index.ts
src/test/approve.spec.ts

Now the API response has a generic and standardized shape, for a successful one we get the data in `response.data`

fix: remove extra data nested property for error handling refactor

---

package.json
src/types/index.ts

Removed properties `commonKey` and `crosschain`

task: remove crosschain and commonKey from tokenData

---

.github/workflows/npm-release.yml
.github/workflows/release-cut.yml
.prettierignore
package.json
yarn.lock

feat: setup release branch cut github action

feat: setup release branch cut github action

---

.github/workflows/release-cut.yml

fix: remove invalid setup secrets step

fix: remove invalid setup secrets step

---

src/index.ts

feat: add axelarscan url param

---

package.json
src/error/index.ts
src/index.ts
src/test/__snapshots__/sdk.spec.ts.snap
src/test/approve.spec.ts
src/test/sdk.spec.ts
src/types/index.ts
src/utils/setAxiosInterceptors.ts

feat: improve error handling

---

.github/workflows/release-cut.yml
.npmignore

Add build action to build dependency step in github branch cut release action.

fix: add build action to build dependency step

---

src/types/index.ts

refactor: chainType

---

README.md
docs/integration.md

Update API docs endpoint link in readme references.

fix: update api docs endpoint in readme

---

jest.config.ts
package.json
src/0xsquid/v1/chains.spec.ts
src/0xsquid/v1/chains.ts
src/0xsquid/v1/route.spec.ts
src/0xsquid/v1/route.ts
src/0xsquid/v1/sdk-info.spec.ts
src/0xsquid/v1/sdk-info.ts
src/0xsquid/v1/status.spec.ts
src/0xsquid/v1/status.ts
src/0xsquid/v1/tokens.spec.ts
src/0xsquid/v1/tokens.ts
src/0xsquid/v1/util.ts
src/constants/chains.ts
src/error/index.ts
src/index.ts
src/test/approve.spec.ts
src/test/constants/chains.ts
src/test/sdk.spec.ts
src/types/index.ts
src/utils/getChainData.ts
src/utils/index.ts
src/utils/setAxiosInterceptors.ts
tsconfig.json

feat: add custom contract calls type

---

.github/workflows/release-cut.yml

fix: release cut action script formatting error

fix: release cut action script formatting error

---

src/0xsquid/v1/status.ts

feat: add timeSpent param in status response

feat: add timeSpent param in status response

---

src/index.ts
src/types/index.ts

- Add override parameter to executeRoute function
- Override property accepts all [TransactionRequest](https://docs.ethers.org/v5/single-page/#/v5/api/providers/types/-%23-providers-TransactionRequest) properties except ["to" | "data" | "value" | "from"] 

feat: add override param to executeRoute function

---

src/index.ts
src/test/approve.spec.ts
src/types/index.ts

feat: add override param to approval action

feat: add override param to approval action

---

src/index.ts

feat: prioritise eip1559 transactions over legacy transaction

feat: prioritise-eip1559-transactions

---

.github/workflows/release-cut.yml

build: add new allowed github actor

---

src/index.ts
src/types/index.ts

handle infinite approval setting in method parameter instead of global config

fix: handle infinite approval setting in method parameter instead of global config

---

src/types/index.ts

feat: add prefer param

---

src/types/index.ts

Add receiveGasOnDestination param to getRoute

feat: add receiveGasOnDestination param to getRoute

---

README.md
docs/integration.md

Update domain name to squidrouter

docs: update squidrouter domain name

---

src/0xsquid/v1/sdk-info.ts
src/types/index.ts

feat: add maintenance flag to sdkinfo route

feat: add maintenance flag to sdkinfo route

---

src/index.ts
src/test/__snapshots__/sdk.spec.ts.snap

Need to have the maintenance attribute in Squid class

fix: provide maintenance attribute in squid class

---

src/index.ts

fix: targetAddress variable deconstruction

---

src/0xsquid/v1/chains.ts
src/types/index.ts

- Add `estimatedExpressRouteDuration` property to chain object

feat: add estimatedExpressRouteDuration property to chain

---

src/0xsquid/v1/tokens.spec.ts
src/0xsquid/v1/tokens.ts
src/types/index.ts

Add optional property handling for commonKey and bridgeOnly TokenDate

fix: add bridgeOnly property

---

src/0xsquid/v1/tokens.spec.ts
src/0xsquid/v1/tokens.ts
src/types/index.ts

- Add missing ibcDenom attribute
- Add according tests

chore: add ibcdenom attribute

---

package.json
src/index.ts
src/types/index.ts
yarn.lock

feat: implement Safe Contract sdk execution

---

package.json
src/index.ts
src/types/index.ts
yarn.lock

This reverts commit cb2f940fe0e68466b2f6171a45a4037a6b29bef9.

Revert "feat: implement Safe Contract sdk execution (#111)"

---

src/types/index.ts

chore: update chainNames

---

src/0xsquid/v1/status.ts
src/index.ts

fix: gasLimit parse and status empty validation

---

src/index.ts
src/types/index.ts

Return unsigned raw tx
```
import dotenv from "dotenv";
import { ethers } from "ethers";
import { keccak256 } from "ethers/lib/utils";
import { Squid } from "./src";
dotenv.config();
const main = async () => {
try {
const sdk = new Squid({ baseUrl: "https://api.0xsquid.com" });
await sdk.init();
const provider = new ethers.providers.JsonRpcProvider(
"https://api.avax.network/ext/bc/C/rpc"
);
const signer = new ethers.Wallet(
process.env.privateKey as string,
provider
);
const { route } = await sdk.getRoute({
toAddress: signer.address,
fromChain: 43114,
fromToken: sdk.tokens.find(
t => t.symbol.toLowerCase() == "usdc" && t.chainId === 43114
)?.address,
fromAmount: ethers.utils.parseUnits("0.1", 6).toString(),
toChain: 137,
toToken: sdk.tokens.find(
t => t.symbol.toLowerCase() == "axlusdc" …
```

feat: add getRawTxHex method given a route

---

.github/workflows/release-cut.yml
src/index.ts

- Fix getStatus param bug
- Read common headers in getStatus
- Add npm tag option in release cut github action

fix: get status param bug

---

src/0xsquid/v1/sdk-info.ts
src/index.ts
src/types/index.ts

- reflect api change adding optional param maintenanceMessage: string | undefined
- also added automatic sort of import (prettier stuff when saving file)

chore: add maintenance message optional param

---

src/0xsquid/v1/status.spec.ts
src/0xsquid/v1/status.ts
src/types/index.ts

feat: add squidTransactionStatus param

feat: add squidTransactionStatus param

---

CHANGELOG.md
src/0xsquid/v1/route.spec.ts
src/0xsquid/v1/route.ts
src/types/index.ts

collectFees

---

CHANGELOG.md
package.json
src/0xsquid/v1/route.ts
src/0xsquid/v1/status.ts
src/index.ts
src/types/index.ts
yarn.lock

moved cosmos code to latest sdk

---

src/types/index.ts

added required fromAddress param for getting route

---

package.json
src/adapter/HttpAdapter.ts
src/handlers/evm/index.ts
src/handlers/evm/utils.ts
src/index.ts
src/types/status.ts
yarn.lock

chore: SDK V2 setup

---

src/index.ts

TLDR; Use Stargate client `sign` instead of `signAndBroadcast`
- At the moment our SDK for `executeRoute` EVM is doing: `tx = await signer.sendTransaction(tx)`  Then on the frontend we need to do an additional `tx.wait()`  to know when the tx is done on source, etc. 
- this is totally fine and what we want
- On cosmos we were doing `await signer.signAndBroadcast()` 
- The problem with that is that the callback is sent too late in term of UX, and the user is left with the screen "Confirm in wallet" even if he just did. The way to fix this is to use `signer.sign`in the SDK and let the frontend do the `signer.broadcastTx()`. 
- This way we also have a similar approach in evm and cosmos, and this fixes the ux problem
Please add some evidence like screenshots …

chore: cosmos execute: sign without broadcasting tx

---

src/handlers/cosmos/index.ts
src/types/index.ts

Manual Cherry-pick cosmos signature change (remove broadcast)

chore: v2 sign cosmos without broadcast

---

src/handlers/evm/index.ts

Got the issue mentioned below with ethers v6 approve call
https://github.com/ethers-io/ethers.js/issues/3830
Fixed by encoding it manually
Might be other ways to fix that.

fix: manual tx encoding for token spend approval

---

src/index.ts

See https://github.com/0xsquid/squid-sdk/pull/217
This implementation is async, because needs to fetch token prices first.

feat: get from amount

---

src/index.ts
src/services/getEvmBalances.ts

Use the correct rpc url for each chain

fix: use a different rpc url for each chain

---

src/index.ts

Fetch token prices at run-time for `getFromAmount()` method and use prices fetched at initialization time as default if there was an error.
Also implement `getTokenPrice()`

feat: fetch token prices at runtime

---

package.json
src/handlers/cosmos/index.ts
src/handlers/evm/index.ts
src/index.ts
yarn.lock

chore: update types config and fix types issues

---

src/index.ts
src/utils/cosmos.ts
src/utils/evm.ts
src/utils/index.ts

Move EVM and Cosmos utils to `utils/evm.ts` and `utils/cosmos.ts`.
- closes 0xsquid/squid-core#2736
- [Zenhub issue](https://app.zenhub.com/workspaces/squid-62f41ece0f99c000158e872d/issues/gh/0xsquid/squid-core/2736)

Refactor v2/utils

---

package.json
yarn.lock

chore: update squid types and ethers

---

src/services/getEvmBalances.ts

fix: bignumber formatting

---

src/services/getEvmBalances.ts

Avoid to throw an error if the value Bignumber is trying to parse is undefined

fix: handle possible undefined value that could throw bignumber error

---

package.json
yarn.lock

chore: update squid types package

---

package.json
src/index.ts
yarn.lock

chore: update types

---

package.json
src/types/ethers.ts
yarn.lock

fix: ethers v5 wallet type

---

.github/workflows/release-cut.yml
.gitignore

Removed user from release cut approval list

---

.github/workflows/release-cut.yml

Adjusted release cut permissions

---

package.json
yarn.lock

chore: update squid types

---

src/index.ts

- Refactor existing method `getTokenPrice` to use the new endpoint `/tokens`
- Adds `getAllTokensWithPrice`
- Adds `getAllTokensWithPriceForChain`

feat: new sdk method to get usd prices

---

src/index.ts
src/types/index.ts

chore: add option to use signAndBroadcast instead of sign

---

package.json

- [v1] fix: set package version to latest npm version 

[v1] fix: set package version to latest npm version

---

package.json
yarn.lock

https://github.com/orgs/0xsquid/projects/3/views/31?pane=issue&itemId=61800515

feat: improve hook type

---

package.json
src/handlers/cosmos/index.ts
yarn.lock

- migrated logic from V1 sdk for being able to sign wasm tx type

wasm tx's signing

---

src/handlers/evm/index.spec.ts
src/index.spec.ts
src/utils/TokensChains.spec.ts

- adds tests for public sdk methods
run `yarn test`

Test v2/handlers tests

---

src/constants/index.ts
src/handlers/evm/index.ts
src/handlers/evm/utils.ts

fix: approval address check

---

CHANGELOG.md
package.json
src/handlers/cosmos/index.ts
yarn.lock

fix estimation; bump cosmjs versions

---

.github/workflows/lint.yml
.github/workflows/unit-tests.yml
package.json
src/types/ethers.ts
yarn.lock

Fix yarn audit vulnerabilities

fix: audit vulnerabilities

---

.github/workflows/lint.yml
.github/workflows/release-cut.yml
.github/workflows/unit-tests.yml
CHANGELOG.md
package.json
src/constants/index.ts
src/handlers/cosmos/index.ts
src/handlers/evm/index.ts
src/handlers/evm/utils.ts
src/handlers/index.ts
src/handlers/solana/index.ts
src/index.spec.ts
src/index.ts
src/types/ethers.ts
src/types/index.ts
src/utils/numbers.spec.ts
src/utils/numbers.ts
yarn.lock

- Restore code to v2.9.1 commit
- Re-add and upgrade it-release package

Restore/v2 code to v2.9.1

---

src/types/index.ts

Add quote id for attaching quote to status response

add quote id
